/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vue;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import metier.*;

/**
 *
 * @author François, Elliot
 */
public class Accueil extends javax.swing.JFrame{
	
	public Graphe graphePrincipal;

	/**
	 * Creates new form Accueil
	 */
	public Accueil() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelAccueil = new javax.swing.JPanel();
        jButtonImporter = new javax.swing.JButton();
        jLabelMessageGraphe = new javax.swing.JLabel();
        jPanelEcran0 = new javax.swing.JPanel();
        jButtonSommets = new javax.swing.JButton();
        jButtonAretes = new javax.swing.JButton();
        jLabelTitreChoix = new javax.swing.JLabel();
        jPanel_resultat = new javax.swing.JPanel();
        jLabelRecap = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jPanelEcran1 = new javax.swing.JPanel();
        jPanelEcran2 = new javax.swing.JPanel();
        jPanelEcran3 = new javax.swing.JPanel();
        jPanelEcran4 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFichier = new javax.swing.JMenu();
        jMenuItemImporter = new javax.swing.JMenuItem();
        jMenuItemInformations = new javax.swing.JMenuItem();
        jMenuItemQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Accueil");

        jButtonImporter.setText("Importer un graphe");
        jButtonImporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImporterActionPerformed(evt);
            }
        });

        jLabelMessageGraphe.setText("En attente d'importation d'un graphe...");

        javax.swing.GroupLayout jPanelAccueilLayout = new javax.swing.GroupLayout(jPanelAccueil);
        jPanelAccueil.setLayout(jPanelAccueilLayout);
        jPanelAccueilLayout.setHorizontalGroup(
            jPanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccueilLayout.createSequentialGroup()
                .addGroup(jPanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccueilLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabelMessageGraphe))
                    .addComponent(jButtonImporter))
                .addContainerGap())
        );
        jPanelAccueilLayout.setVerticalGroup(
            jPanelAccueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccueilLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jLabelMessageGraphe)
                .addGap(173, 173, 173)
                .addComponent(jButtonImporter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Accueil", jPanelAccueil);

        jButtonSommets.setText("Sommets");
        jButtonSommets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSommetsActionPerformed(evt);
            }
        });

        jButtonAretes.setText("Arêtes");

        jLabelTitreChoix.setText("Afficher les informations sur :");

        javax.swing.GroupLayout jPanel_resultatLayout = new javax.swing.GroupLayout(jPanel_resultat);
        jPanel_resultat.setLayout(jPanel_resultatLayout);
        jPanel_resultatLayout.setHorizontalGroup(
            jPanel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultatLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabelRecap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_resultatLayout.setVerticalGroup(
            jPanel_resultatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_resultatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRecap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jScrollPane3.setViewportView(jList3);

        javax.swing.GroupLayout jPanelEcran0Layout = new javax.swing.GroupLayout(jPanelEcran0);
        jPanelEcran0.setLayout(jPanelEcran0Layout);
        jPanelEcran0Layout.setHorizontalGroup(
            jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcran0Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_resultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEcran0Layout.createSequentialGroup()
                        .addGroup(jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitreChoix)
                            .addGroup(jPanelEcran0Layout.createSequentialGroup()
                                .addComponent(jButtonSommets)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAretes)))
                        .addContainerGap(623, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEcran0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanelEcran0Layout.setVerticalGroup(
            jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEcran0Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitreChoix)
                .addGap(7, 7, 7)
                .addGroup(jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSommets)
                    .addComponent(jButtonAretes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_resultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEcran0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("0-distance", jPanelEcran0);

        javax.swing.GroupLayout jPanelEcran1Layout = new javax.swing.GroupLayout(jPanelEcran1);
        jPanelEcran1.setLayout(jPanelEcran1Layout);
        jPanelEcran1Layout.setHorizontalGroup(
            jPanelEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanelEcran1Layout.setVerticalGroup(
            jPanelEcran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("1-distance", jPanelEcran1);

        javax.swing.GroupLayout jPanelEcran2Layout = new javax.swing.GroupLayout(jPanelEcran2);
        jPanelEcran2.setLayout(jPanelEcran2Layout);
        jPanelEcran2Layout.setHorizontalGroup(
            jPanelEcran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanelEcran2Layout.setVerticalGroup(
            jPanelEcran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("2-distance", jPanelEcran2);

        javax.swing.GroupLayout jPanelEcran3Layout = new javax.swing.GroupLayout(jPanelEcran3);
        jPanelEcran3.setLayout(jPanelEcran3Layout);
        jPanelEcran3Layout.setHorizontalGroup(
            jPanelEcran3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanelEcran3Layout.setVerticalGroup(
            jPanelEcran3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab(">= 2-distance", jPanelEcran3);

        javax.swing.GroupLayout jPanelEcran4Layout = new javax.swing.GroupLayout(jPanelEcran4);
        jPanelEcran4.setLayout(jPanelEcran4Layout);
        jPanelEcran4Layout.setHorizontalGroup(
            jPanelEcran4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        jPanelEcran4Layout.setVerticalGroup(
            jPanelEcran4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("p-distance", jPanelEcran4);

        jMenuFichier.setText("Fichier");

        jMenuItemImporter.setText("Importer");
        jMenuFichier.add(jMenuItemImporter);

        jMenuItemInformations.setText("Informations");
        jMenuFichier.add(jMenuItemInformations);

        jMenuItemQuitter.setText("Quitter");
        jMenuFichier.add(jMenuItemQuitter);

        jMenuBar.add(jMenuFichier);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImporterActionPerformed
        JFileChooser choixFichier = new JFileChooser();
		int option = choixFichier.showOpenDialog(null);
            if(option == JFileChooser.APPROVE_OPTION){
               File file = choixFichier.getSelectedFile();
			   jLabelMessageGraphe.setText("Graphe correctement importé : " + file.getName());
			try {
				graphePrincipal = new Graphe(file.getName());
			} catch (IOException ex) {
				Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
			}
			}
			
    }//GEN-LAST:event_jButtonImporterActionPerformed

    private void jButtonSommetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSommetsActionPerformed
        int nbNode = graphePrincipal.infographe().get(0);
        int nbVilles = graphePrincipal.infographe().get(1);
        int nbResto = graphePrincipal.infographe().get(2);
        int nbLoisir = graphePrincipal.infographe().get(3);
        jLabelRecap.setText("votre graphe posséde : "+nbNode+"  Noeuds,"+nbVilles+" Villes,"+nbResto+" Restaurant,"+nbLoisir+" lieux de loisir,");

    }//GEN-LAST:event_jButtonSommetsActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Accueil().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAretes;
    private javax.swing.JButton jButtonImporter;
    private javax.swing.JButton jButtonSommets;
    private javax.swing.JLabel jLabelMessageGraphe;
    private javax.swing.JLabel jLabelRecap;
    private javax.swing.JLabel jLabelTitreChoix;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFichier;
    private javax.swing.JMenuItem jMenuItemImporter;
    private javax.swing.JMenuItem jMenuItemInformations;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JPanel jPanelAccueil;
    private javax.swing.JPanel jPanelEcran0;
    private javax.swing.JPanel jPanelEcran1;
    private javax.swing.JPanel jPanelEcran2;
    private javax.swing.JPanel jPanelEcran3;
    private javax.swing.JPanel jPanelEcran4;
    private javax.swing.JPanel jPanel_resultat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
